### ISSUE TITLE
Restructuring the UI code

### ISSUE THREAD

**Issue by gopalkoduri** [mpetyx/DarwinsMusic#3]
Need to arrange the folder structure in such a way that it is intuitive to browse through and understand it. There should be a clear distinction between styles/scripts/html. The external libraries should also be neatly placed.

**Comment by zaen** [comment]
Done.

The UI code now structured as expected:

/css --- contains all styles
/js --- contains all java script (library, profile)
/data --- contains all JSON data
index.html --- one and only one our html page

**Comment by gopalkoduri** [comment]
You can get rid of the data/ folder inside web/ folder, and use DarwinsMusic/data/ folder instead. That would be more clean as the src/ folder will have only the source code and nothing else.
