### ISSUE TITLE
Restructuring the server code

### ISSUE THREAD

**Issue by gopalkoduri** [mpetyx/DarwinsMusic#7]

**Comment by mpetyx** [comment]
i did most of it, but what do you have in mind in detail?

**Comment by gopalkoduri** [comment]
See the [proposed restructuring](https://github.com/mpetyx/DarwinsMusic/blob/master/proposed_restructing.txt), the server code should go inside DarwinsMusic/src/ folder. And all the data files (.json, .xml etc) should go to DarwinsMusic/data/ folder.
